import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { Lexend } from "next/font/google";

import Layout from "@/src/components/layout/Layout";

import "./globals.css";

const lexend = Lexend({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({
  children,
  params: { locale = "pl" },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) => {
  let messages;
  try {
    messages = (await import(`../../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={lexend.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Layout>{children}</Layout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
